# This is a basic workflow to help you get started with Actions

name: Generate data.js

# Controls when the action will run. 
on:
  workflow_run:
    workflows: [ "Validate JSON" ]
    types:
      - completed

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate data.js
        run: |
          cd data
          echo 'jsonData='| cat - data.json > temp && mv -f temp data.js
      - name: Commit changes
        run: |
          git config --local user.name "MozartusBot"
          git add data
          git commit -m "Generate data.js"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          force: true
          
